set nocompatible              " be iMproved, required

filetype off                  " 必须要添加

filetype plugin on

let mapleader = ","

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugin 'Valloric/YouCompleteMe'

""""" 注释插件
Plugin 'scrooloose/nerdcommenter'
" 注释的时候自动加个空格, 强迫症必配
let g:NERDSpaceDelims=1

""""" 自动配对
Plugin 'jiangmiao/auto-pairs'

" 你的所有插件需要在下面这行之前
call vundle#end()            " 必须
filetype plugin indent on    " 必须 加载vim自带和插件相应的语法和文件类型相关脚本


" Switch syntax highlighting on, when the terminal has colors
if has("gui_running") && !exists("syntax_on")
  syntax on
endif

" Javascript syntax hightlight
syntax enable

set number

" Set syntax highlighting for specific file types
autocmd BufRead,BufNewFile Appraisals set filetype=ruby
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd Syntax javascript set syntax=jquery

" Color scheme
colorscheme molokai
highlight NonText guibg=#060606
highlight Folded  guibg=#0A0A0A guifg=#9090D0

"set mouse=a         " 启用鼠标的使用

:nmap <C-N><C-N> :set invnumber<CR> " 开关行号显示

" 配置去解决排版的问题，比如字符编码和缩 进等问题。
