# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
# (****) ZSH_THEME="risto"
#ZSH_THEME="rkj-repos"
#ZSH_THEME="wedisagree"
ZSH_THEME="crazycode"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias gs="stree"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ant autojump brew cap coffee gem git git-flow github gradle golang history-substring-search mvn osx rails rake ruby rvm rsync screen tmux tmuxinator sbt svn scala bundler virtualenv safe-paste vagrant docker)

source $ZSH/oh-my-zsh.sh

alias v=vagrant

# Customize to your needs...
export PLAY_HOME=$HOME/opt/play-1.2.7

export ANDROID_HOME=$HOME/opt/android-sdk-macosx
# please run "brew install coreutils" first.

export EDITOR=jed
export VISUAL=jed

export MULE_HOME=$HOME/opt/mule-standalone-3.4.0
export PATH=$PATH:$MULE_HOME/bin

export GROOVY_HOME=/usr/local/opt/groovy/libexec
#export GRADLE_HOME=$HOME/opt/gradle-1.8
export PATH=$(brew --prefix coreutils)/libexec/gnubin:/usr/local/sbin:/usr/local/bin:$PATH:$HOME/bin:$HOME/opt/play-1.2.7:$HOME/opt/activator-1.2.10:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:/usr/local/sbin:$HOME/.cabal/bin
export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"

#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home
export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)
export JAVA_OPTS="-server -Xmx1024m -XX:PermSize=64M -XX:MaxPermSize=256m"
export RSENSE_HOME=$HOME/opt/rsense-0.3

#THIS MUST BE AT THE END OF THE FILE FOR JENV TO WORK!!!
#[[ -s "$HOME/.jenv/bin/jenv-init.sh" ]] && source "$HOME/.jenv/bin/jenv-init.sh"
#

# fix git svn issue.
export PERL5LIB="/Applications/Xcode.app/Contents/Developer/Library/Perl/5.16/darwin-thread-multi-2level"

# for docker
export DOCKER_HOST=tcp://$(boot2docker ip 2>/dev/null):2375
#export DOCKER_HOST=tcp://127.0.0.1:2375
#export DOCKER_HOST=tcp://192.168.59.103:2375

PATH=$JAVA_HOME/bin:$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

